# Configuration file documentation:
# https://github.com/kriskbx/gitlab-time-tracker/blob/master/documentation.md#configuration

# Do not extend the global configuration, create new one:
extend: false

# API Access settings
url: "https://gitlab.dev.ifs.hsr.ch/api/v4/"
# Note: The token will be specified on the command line.

# Report Settings
showWithoutTimes: true
hoursPerDay: 8.6
daysPerWeek: 1
closed: true
timeFormat: "[%sign][%hours_overall]"
dateFormat: "YYYY-MM-DD HH:mm:ss"
issueColumns:
  - iid
  - title
  - state
  - milestone
  - labels
  - spent
  - total_spent
  - total_estimate
output: markdown

